AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Controller

Resources:
  APIHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      CodeUri: build/libs/app-0.1-all.jar
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      MemorySize: 512
      Timeout: 60
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/'
            Method: post
